services:
  - type: web
    name: nlp-analyzer
    runtime: python
    buildCommand: ./build.sh  # ⬅️ add this line
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13